# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"


variables:
    # Workflow inputs given to nextflow.
    # The workflow should define `--out_dir`, the CI template sets this.
    # Only common file inputs and option values need to be given here
    # (not things such as -profile)
    NF_WORKFLOW_OPTS: "--fastq test_data"
    NF_IGNORE_PROCESSES: "extractKraken2Reads,extractMinimap2Reads,minimap2,mergeBAM"
    CI_FLAVOUR: "new"

aws-run:
    artifacts:
        when: always
        paths:
            - ${CI_PROJECT_NAME}
            - .nextflow.log
        exclude: [] # give me everything pal
    allow_failure: true


docker-run:

    # Remove this directive in downstream templates
    tags: [] # no need for big ram

    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "kraken2", "minimap2", "kraken2-single-file", "batch"
            ]
    rules:
     - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
       when: never
     - if: $MATRIX_NAME == "kraken2"
       variables:
          NF_WORKFLOW_OPTS: "--fastq test_data --read_limit 50"
          NF_IGNORE_PROCESSES: extractMinimap2Reads,minimap2,mergeBAM
     - if: $MATRIX_NAME == "batch"
       variables:
          NF_WORKFLOW_OPTS: "--fastq test_data --read_limit 50 --batch_size 3"
          NF_IGNORE_PROCESSES: extractMinimap2Reads,minimap2,mergeBAM
     - if: $MATRIX_NAME == "kraken2-single-file"
       variables:
          NF_WORKFLOW_OPTS: "--fastq test_data/barcode01/reads.fastq.gz"
          NF_IGNORE_PROCESSES: extractMinimap2Reads,minimap2,mergeBAM
     - if: $MATRIX_NAME == "minimap2"
       variables:
          NF_WORKFLOW_OPTS: "--fastq test_data --minimap2 --minimap2filter '9606,1404' --classifier minimap2"
          NF_IGNORE_PROCESSES: extractKraken2Reads,kraken2,mergeKrakenFiltered


